### ISSUE TITLE
o.json is no longer used and has erroneous blocked content

### ISSUE THREAD

**Issue by jasonedison** [atomantic/henpin#4]
hicetnunc.xyz is now only using the w.json block list.

https://github.com/hicetnunc2000/hicetnunc/blob/d35ab0decddb45758afe0b2b040dca852ed3215a/src/pages/display/index.js#L24-L29

`filterFeeds` is the only function within the UI codebase that uses the o.json loaded blocklist, but nothing is currently using that function to filter content on the site: https://github.com/hicetnunc2000/hicetnunc/search?q=filterFeeds

The o.json block file contains some objects that were added by mistake and `should not be blocked`. A few of mine are among them. Example:

https://www.hicetnunc.xyz/objkt/6300

Discussion in discord: https://discord.com/channels/759930487946215444/818877118489690182/903764961577275402

**Comment by atomantic** [comment]
I see! Fixed in 1.3.1 -- only using the wallet blocklist now.
