### ISSUE TITLE
Add timestamps to console with 'console-stamp'

### ISSUE THREAD

**Issue by user90210** [atomantic/henpin#5]
By installing [console-stamp](https://www.npmjs.com/package/console-stamp)

`npm install console-stamp`

and adding this line to [henode.js](https://github.com/atomantic/henpin/blob/main/henode.js)
`require( 'console-stamp' )( console );`

you get the following output

![grafik](https://user-images.githubusercontent.com/31575320/140899477-28957fbd-5f1a-4583-b6aa-46e117dd4518.png)

Reason:
Detecting if script has stalled.

**Comment by atomantic** [comment]
added

**Comment by user90210** [comment]
awesome. 

I know I should write a pull request etc and submit it (or something) 
But my understanding of the code and git is really not there yet.

Please also don't see the issues I open as demands, they are just suggestions, and I feel very lucky that you created and updated these scripts :)

**Comment by atomantic** [comment]
I appreciate the input and end user testing :)
